bind:
    ip: 0.0.0.0
    port: 25570
bossBar:
    color: PINK
    division: SOLID
    enable: true
    health: 1
    text: '{"text": "&7You will be &aautomatically reconnected &7in a few moments"}'
brandName:
    content: Lumae Limbo
    enable: true
debugLevel: 2
dimension: THE_END
gameMode: 3
headerAndFooter:
    enable: false
    footer: '{"text": "&9You are in Limbo!"}'
    header: '{"text": "&eWelcome!"}'
infoForwarding:
    secret: <YOUR_SECRET_HERE>
    tokens:
        - <BUNGEE_GUARD_TOKEN>
    type: LEGACY
joinMessage:
    enable: true
    text: '{"text": "&bWelcome to Limbo!\n&7We appreciate your patience while your server restarts"}'
maxPlayers: 100
netty:
    threads:
        bossGroup: 1
        workerGroup: 4
    useEpoll: true
ping:
    description: '{"text": "&9Limbo"}'
    version: Limbo
playerList:
    enable: false
    username: LumaeLimbo
readTimeout: 30000
title:
    enable: true
    fadeIn: 10
    fadeOut: 10
    stay: 100
    subtitle: '{"text": "&7Welcome to Limbo"}'
    title: '{"text": "&9&lLimbo"}'